modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "gtceuao"
version = "${version}"
displayName = "${mod_name}"
authors = "YiranMushroom"
description = "${mod_description}"
logoFile = "icon.png"
displayURL = "${mod_url}"
credits = "GregoriusT, Mr_Touchyou, Zerrens for making GregTech and textures, the GT5u authors and maintainers for providing the original code, and the community."
