modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT License"

[[mods]]
modId = "gtceuao"
version = "${version}"
displayName = "${mod_name}"
authors = "YiranMushroom"
description = "${mod_description}"
logoFile = "icon.png"
displayURL = "${mod_url}"
credits = "Using GTCEu-mordern's codebase in some files. Thanks to the great concept of GregTech to make this game more fun and challenging."

[[dependencies.gtceuao]]
modId = "gtceu"
mandatory = true
versionRange = "[1.2.2,)"
ordering = "NONE"
side = "BOTH"